### ISSUE TITLE
Punctuation customizability

### ISSUE THREAD

**Issue by deathaxe** [jwortmann/brackets-color-scheme#3]
Any chance you define a dedicated color for operators and punctuations (brackets, parens, ...) in order to be able to customize their appereance more easily?

I really like this color scheme, but want operators and punctuation highlighted in different colors for better readability.

With each update it becomes harder or even impossible to do so without literly rewriting the whole color scheme. I really don't want to also need to start to maintain my own color schemes.

**Comment by jwortmann** [comment]
Okay, I will see what I can do. Probably in the next week or next weekend. But maybe it will take a bit more time if I go over the whole scheme to see if I can reorganize or simplify some rules then - I had planned at some time to revise most syntax-specific rules to use the syntax base scope in the selector instead of the language suffix if possible, because I think that's more robust.

I have lots of special rules in the color scheme for syntax-specific `keyword.operator` subscopes, when they are used for actual keywords. It seems that the issue/PR I've opened about this problem a long time ago won't have any outcome in the foreseeable future, but I think I can add variables here for "operator_symbol" (default foreground) and "operator_keyword" (default blue), so that it can easily be customized to highlight both of them with a single color for example.

But it's probably not so easy for punctuations, because they sometimes use different colors here in this scheme. Also in some cases the scopes are applied on top of the underlying token scope (for example in HTML entities like `&nbsp;`, where I'd like them to have the same color of the token - in this case orange) but some other times they are not (e.g. the `@` in Python decorators). Initially I tried to target punctuation scopes only when it's really necessary, but I saw that it can lead to unexpected highlighting for example within string interpolations if the `string` scope is not cleared correctly by the syntax. So I added more of the punctuation scopes to the color scheme some time ago.

I guess I can add another color variable only for when I highlight them with the default foreground (`textcolor`), would that be sufficient?
This would include some fixes/special rules for when another scope different from `punctuation` is used for a punctuation/symbol character, like `storage.modifier.array` in Java/TypeScript, `storage.modifier.reference` in PHP or `support.function.test.begin/end` is Bash. But there would still be various scopes for punctuations with other colors/little color tweaks that would need to be customized manually if desired.

**Comment by deathaxe** [comment]
Thanks!

What I'd like to be able is to tint all operators and brackets/parents (most likely `punctuation.section`) because it helps me much to get quicker overview. Maybe `punctuation.accessor` and `punctuation.separator` may be of interest, too.

If you come accross `punctuation.definition` such as the `&nbsp;` example, the most sufficent solution probably was to just blend them with a blackish color by some percent. 

_Not quite sure, if it is possible to gate it behind some kind of variable though, now that I think about it._

Here's a simple example of some string punctuations rules. But I don't have much of them, because I am too lazy.

```
		{
			"scope": "string punctuation.definition, string punctuation.section",
			"foreground": "color(var(orange) blend(var(grey) 30%))",
		},
		{
			"scope": "string constant.character.entity",
			"foreground": "color(var(orange) blend(var(grey) 50%))",
		},
		{
			"scope": "string constant.character.escape",
			"foreground": "color(var(orange) blend(var(grey) 50%))",
		},
		{
			"scope": "string constant.other.placeholder",
			"foreground": "color(var(orange) blend(var(grey) 30%))",
		},
```

Agree with regards to scope names. I'd try to avoid as much language specific scopes as possible. If really needed use a scheme like `source.foo string.quoted` or so. This may lead to less rules in the long term.

Maybe a well choosen set of variables could also help to create other color scheme variants, like the color16 does. But that's very low prio.

**Comment by jwortmann** [comment]
I have added two color variables `operator_symbol` and `operator_keyword`, so that you should be able to easily adjust the colors for operators now. Here I've considered lamda function arrows as operator symbol too, rather than maybe punctuation or so. What's not affected right now are operator characters within regular expressions, because I use a different color there. Hopefully we find a good way to scope the regex strings derived from a single base syntax in the long term :)

I was a little bit hesitant with these new variables first (using references to other variables so that possible user-customizations for the color variables like `var(blue)` still work as expected), because according to the docs, "variables may be referenced in the global settings and rules", but there is nothing written about references within the "variables" section itself. But as long as nobody accidentally creates an infinite loop with variables, it seems to work fine, and I've seen various other color schemes do the same.

I will look if I can add another variable for punctuations shortly. Right now I don't have a general rule for `punctuation.section`, but only a few rules where it is necessary to override a color in a certain syntax. Maybe I can generalize them all with a single rule. Do you like to have different colors for parens/brackets (`punctuation.section`) and for other punctuations (`punctuation.separator`, `punctuation.accessor`, `punctuation.terminator`), or would it be okay to lump them all together?

**Comment by deathaxe** [comment]
Regexp is indeed separate a topic.

**Comment by jwortmann** [comment]
There is another color variable `punctuation` now, which should affect the punctuations with the default foreground color (i.e. it doesn't apply to most `punctuation.definition` scopes as in tag or string punctuations, and I have very few exclusions like `punctuation.separator.path` in URLs which I don't like a lot and prefer to be highlighted similar to the original themes).

If you want a different highlighting color only for brackets/parens, then this should be possible with an additional rule like
```json
        {
             "scope": "punctuation.section, punctuation.definition.group, punctuation.definition.generic",
             "foreground": "white"
        },
```
It should cover most bracket types, with a few exception that I would consider as bug/inconsistency in a syntax, for example there are a few deviating scopes for braces in string interpolations or in Python `punctuation.section` is sometimes used for `:`.

The `string constant.character` example is indeed something that could need a bit improvement, but I'm unsure about the color, so I think I will leave it for now.

I will wait a bit before I make a new release to see if I missed some bugs and to be sure that everything works as expected. Please write if it works for you or if you have more suggestions.

**Comment by deathaxe** [comment]
Thanks again. Looks good so far.

Interpolation may need some refinements. It's not yet completed to be deployed to all syntaxes. If you find such nitpicks feel free to add a small issue at the Packages repo. Now that we have write access, we may probably be able to find and merge solutions more quickly and in smaller steps.

It's not a big deal for me to create some extra rules for the color scheme to color certain tokens different. The only important precondition for consistent results are as generic as possible selectors.

**Comment by deathaxe** [comment]
While skimming through various syntaxes I found `punctuation.definition` not highlighted in Erlang macros.

```
#record{field1="val1", Field2=3, field3, 'Field-4'={}, _=atom}
```

![grafik](https://user-images.githubusercontent.com/16542113/132133663-dd0a8aa9-b01a-4e99-8104-df5e88e58968.png)

I therefore wonder, whether applying `punctuation` color might be a good basic value for such situations.

I added the following lines to my user override

```
{
    "name": "Punctuation",
    "scope": "punctuation, punctuation.definition, punctuation.section",
    "foreground": "var(punctuation)"
},
```

![grafik](https://user-images.githubusercontent.com/16542113/132133710-ed36e5fb-0e9b-4122-ab58-0da5c5c8c4e1.png)

**Comment by jwortmann** [comment]
I avoided to define a general rule for `punctuation.definition` on purpose, because such punctuation symbols have a variety of colors in this scheme and they are not always, but often applied on top of another scope for a certain token. For example string quotes, `punctuation.definition.preprocessor` for the `#` of preprocessor keywords in C#, the leading `$` for variables in PHP, or the `&` in `&nbsp;`. 
By having no general rule for `punctuation.definition`, the underlying color is applied, which is what I want to achieve in most of the cases. So I think this is a better default, than applying the `var(punctuation)` color there. Here is a good example from the PHP syntax tests:

![php](https://user-images.githubusercontent.com/6579999/132336917-cb73cfa8-9a77-430f-9097-aee593285fc3.png)

For normal occurences the `$` is white, but if it is a function parameter the `$` is orange like the parameter name, but both times of course they use the same `punctuation.definition.variable` scope. If I had a general rule for `punctuation.definition`, I would have to fiddle with meta scopes etc. to achieve that highlighting. I saw this example just now coincidentally, but there are probably plenty of others that I don't know about.

If you want to adjust the colors for all such definition symbols only a little bit, you could try something like
```json
{
    "scope": "punctuation.definition",
    "foreground_adjust": "lightness(- 15%) saturation(- 25%)",
    "background": "#1d1f21"
},
```
and it should work even where I have rules with more specific scopes for certain colors. But it might not look optimal for all colors, so perhaps it needs a bit tweaking for some colors.

Btw, `punctuation.section` should already be covered by the rules I added recently.

Regarding the `#record` example in Erlang: I have never used Erlang, so I don't really know what this record syntax means, but since you wrote that it is a macro, I could imagine to color both the punctuation and keyword with purple, similar to the preprocessor keywords in C/C#. I already have a rule in this color scheme for macros in the Julia language, which looks like this, and I think it is quite nice:

![julia](https://user-images.githubusercontent.com/6579999/132336898-64bae5ac-39b3-453a-9acd-16087993e52b.png)

The scopes used here are `variable.macro`/`support.function.macro` and `punctuation.definition.macro`, corresponding with Python decorators. The scopes in Erlang seem quite specific to this "record", so I'd have to take a closer look whether it is applicable and would work there too. But I hope what I wrote above explains why I'd prefer to avoid a general rule for `punctuation.definition` ;)

**Comment by deathaxe** [comment]
Can follow your intention. Maybe it's just one of some special cases in Erlang in which the punctuation is not stacked on top of the normal identifier scope. I did that this way as it is somehow unclear whether it realy belongs to the identifier or is used as some kind of accessor in `expr#record{...}`.

Can easily tweak that on my end.

**Comment by jwortmann** [comment]
I have pushed a new tag for Package Control, so I will close this issue now. I can add some tweaks if we find possible improvements, but I think most of it works well now.
