### ISSUE TITLE
We don't need yet another anti-color-scheme

### ISSUE THREAD

**Issue by deathaxe** [jwortmann/brackets-color-scheme#4]
IMHO, line 2 looks totally broken with nothing being highlighted.

![grafik](https://user-images.githubusercontent.com/16542113/191790515-b490a933-409c-4f50-b6be-8ec68b37fc07.png)

One of your recent changes even broke my local overrides to highlight types. Please don't add too many too special spacial cases which noone can override anymore.

Tons of rules just to vanish all valid highlighting.

**Comment by jwortmann** [comment]
Yes, I removed the highlighting for unrecognized class-names for Java and a few other syntaxes in the latest release. For the reasoning about this, see the [release notes](https://github.com/jwortmann/brackets-color-scheme/releases/tag/v2.8.0). I had done this already earlier for some other languages like JavaScript (https://github.com/jwortmann/brackets-color-scheme/commit/6d84cd37250b4f6b0ef7f79c56fd6078baaaded7) or PHP, and from all of those languages, Ruby is the only one where class names are highlighted in the original Adobe Brackets editor. I think it's fine to have intrinsics / builtin classes highlighted in blue, but especially in Java in my opinion it doesn't look very good if every user-defined class is blue too - because keywords and intrinsics just doesn't stand out enough anymore in that case. While I agree that it's not optimal that such class names are not highlighted at all now, I think it's still better than blue. Ideally there would be a unique new color for classes and types in the Brackets schemes, but I'm reluctant to add a new color by myself for this (in general the color scheme should stick to the look of the Adobe Brackets themes).

Especially in the new Java syntax it is annoying if you type within a method on a particular line preceding a variable declaration on a later line, then the identifier on the current line is (potentially) wrongly highlighted as `storage.type.class`, while also the classname on the next line temporarily loses its highlighting.
```java
class MyClass {
    public static void main(String[] args) {

        myVar   // <- currently typing

        Foo a = new Foo();

    }
}
```
That is maybe consistent with how the compiler would parse the source code at that current point in time, but it is highly impractical for users writing the source code (there is a pretty strong convention of PascalCase for classnames and also nobody would write a variable declaration this way over multiple lines, with only the classname on a single line and the rest on a separate line after that). This applies as well if the currently written part is something like `myVar.someMethod`.
By not highlighting the `storage.type.class` scope anymore, I can avoid all of this.

But if you want them to be highlighted (in all relevant syntaxes), it should be possible with minimum effort by adjusting the color for the `"type"` variable as described in the release notes or in the readme. I hope that is sufficient for you to resolve the problem.

> Please don't add too many too special spacial cases which noone can override anymore.

Actually I tried to define the scope selectors in a relatively generic way. For the new Java syntax I used [`source.java storage.type.class`](https://github.com/jwortmann/brackets-color-scheme/blob/775caf56b6bf9994e8b8ff01f722a2ff422d6278/Brackets%20Dark.sublime-color-scheme#L868), so a user-rule with `storage.type.class.java` should take precedence.

It might be possible to make the linked selector even more generic as `source.java storage.type`, but then I would have to also target `storage.type.void`, `storage.type.primitive` and `storage.type.variant` specially (to keep them highlighted blue), and doing that would not be future-proof in case new sub-scopes would be added.

**Comment by deathaxe** [comment]
> adjusting the color for the "type" variable as described in the release notes or in the readme

Gotcha! Just was annoyed by noticing different/broken highlighting and various personal overides being broken. Too busy to study readme for differences. I highlight all types violet to avoid conflicts with blue.

> While I agree that it's not optimal that such class names are not highlighted at all now, I think it's still better than blue.

Not in the given example, no.

> That is maybe consistent with how the compiler would parse the source code at that current point in time, but it is highly impractical for users writing the source cod

Fixing that would significantly drop syntaxes performance and increase complexity due to all the branching.

You'll see such effects in various places of incomplete statements across syntax so thats no point of special complaint for Java!
