### ISSUE TITLE
PHP function colours broken in sublime 4143

### ISSUE THREAD

**Issue by droidcaptcha** [jwortmann/brackets-color-scheme#5]
PHP function colours appear to be broken with latest build, used to show as purple are now showing as white (used default colours and unmodified colour theme)

**Comment by jwortmann** [comment]
Thanks for the report! Could you please paste a code example and/or screenshot, so I can see where exactly the problem is?

The following minimum example looks fine to me, but I'm not a PHP user myself, so I could likely miss something or just don't know the right syntax you are referring to.

![php](https://user-images.githubusercontent.com/6579999/202164069-34e6a454-336e-41fd-8b0b-7f251b5f58e2.png)

**Comment by droidcaptcha** [comment]
Hi, sorry I should have been more clear for you. So in your example the purple colour is what it used to be. I have attached a screenshot of what is happening now . 
![Screenshot 2022-11-16 at 11 42 41 am](https://user-images.githubusercontent.com/117905793/202171796-80090ad2-02c8-48da-9e92-2d6ac1e4b434.jpg)

**Comment by jwortmann** [comment]
Hm, actually I don't see this happening here.

![test](https://user-images.githubusercontent.com/6579999/202233379-d432d4cd-ba26-4f42-89c3-3e94f0818c13.png)

Are you sure that you don't have any overrides in place for the syntax or color scheme?
Can you check if it happens in other color schemes too, and what does it show for the scope name if you place the cursor within `function_example` and use *Tools > Developer > Show Scope Name* from the main menu?

**Comment by droidcaptcha** [comment]
Hi, apologies for this but I removed and installed the package again and functions are now showing correctly. Must have been a conflict with the latest sublime build or something when upgrading. I have closed this now. Thanks again for the suggestions and support
